export const EVENT_TYPE = {
  FORKLIFT_ADDRESS_ENTER: 'FORKLIFT_ADDRESS_ENTER',
  FORKLIFT_ADDRESS_LEAVE: 'FORKLIFT_ADDRESS_LEAVE',
  FORKLIFT_PALLET_PICK: 'FORKLIFT_PALLET_PICK',
  FORKLIFT_PALLET_DROP: 'FORKLIFT_PALLET_DROP',
  PALLET_STORED: 'PALLET_STORED',
  PALLET_RETRIEVED: 'PALLET_RETRIEVED',
  OPERATION_REJECTED: 'OPERATION_REJECTED',
  EVENT_RECONCILED: 'EVENT_RECONCILED',
} as const;

export type EventTypeCode = (typeof EVENT_TYPE)[keyof typeof EVENT_TYPE];

export const EVENT_LAYER = {
  RAW: 'raw',
  INFERRED: 'inferred',
  RECONCILIATION: 'reconciliation',
} as const;

export type EventLayer = (typeof EVENT_LAYER)[keyof typeof EVENT_LAYER];
